version: '2'
services:
    app:
        build:
            context: ./
            dockerfile: app.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=db"
    web:
        build:
            context: ./
            dockerfile: web.dockerfile
        working_dir: /var/www
        volumes_from:
            - app
        ports:
            - 8080:80

    db:
        image: mysql:5.7
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            - "MYSQL_DATABASE=gab"
            - "MYSQL_USER=gab"
            - "MYSQL_PASSWORD=password"
            - "MYSQL_ROOT_PASSWORD=password"
        ports:
            - "33061:3306"

volumes:
    dbdata:
